namespace WorldCup.Domain.Entities;

/// <summary>
/// Represents an API key generated by a user for accessing REST endpoints
/// </summary>
public class ApiKey
{
    public Guid Id { get; set; }
    public string Key { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public Guid UserId { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? ExpiresAt { get; set; }
    public bool IsActive { get; set; } = true;
    
    public User User { get; set; } = null!;
}